/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class ViewModificar extends javax.swing.JFrame {

    Conexion enlace = new Conexion();
    Connection conect = enlace.conectar();
    
    public ViewModificar() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxt_cedula = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jLabel_aviso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxt_nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxt_fecha = new javax.swing.JTextField();
        jTxt_telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxt_sexo = new javax.swing.JTextField();
        jTxt_direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxt_estado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jLabel_verificacion = new javax.swing.JLabel();
        jButton_actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Volver.setText("Volver");
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setText("MODIFICAR - DATOS DE CLIENTE");

        jLabel1.setText("Ingrese la cédula:");

        jTxt_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_cedulaActionPerformed(evt);
            }
        });

        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel6.setText("Dirección");

        jTxt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_nombreActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha nac.");

        jLabel4.setText("Teléfono");

        jLabel5.setText("Sexo");

        jLabel7.setText("Estado civil");

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaCliente);

        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTxt_nombre))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTxt_sexo)
                                                .addComponent(jTxt_telefono)))))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTxt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTxt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTxt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(62, 62, 62)))
                            .addComponent(jButton_buscar))))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_verificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Volver)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_actualizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTxt_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTxt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTxt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTxt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_verificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Volver)
                    .addComponent(jButton_actualizar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverActionPerformed
        ViewRegistroCustomer login = new ViewRegistroCustomer();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_VolverActionPerformed

    private void jTxt_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_cedulaActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        
        String ced = jTxt_cedula.getText();
        String dato;
        
        DefaultTableModel tcliente = new DefaultTableModel();
        tcliente.addColumn("CÉDULA");
        tcliente.addColumn("NOMBRE");
        tcliente.addColumn("TELÉFONO");
        tcliente.addColumn("SEXO");
        tcliente.addColumn("ESTADO");
        tcliente.addColumn("DIRECCIÓN");
        tcliente.addColumn("FECHA NAC.");
        tablaCliente.setModel(tcliente);
        
        //se realiza un arreglo
        String []datos = new String[7];
        
        try {
            
            Statement leer = conect.createStatement();
            ResultSet result = leer.executeQuery("select * from tabla1"); //Se verifica toda la información de la tabla
            while (result.next()) { //mientras se encuentren valores siguientes
                dato = result.getString(1);
                if(dato.equals(ced)){
                    jLabel_aviso.setText("Se hayo ID en la BD");
                    jTxt_nombre.setText(result.getString(2));
                    jTxt_nombre.setEnabled(false);
                    jTxt_telefono.setText(result.getString(3));
                    jTxt_sexo.setText(result.getString(4));
                    jTxt_sexo.setEnabled(false);
                    jTxt_estado.setText(result.getString(5));
                    jTxt_direccion.setText(result.getString(6));
                    jTxt_fecha.setText(result.getString(7));
                    jTxt_fecha.setEnabled(false);
                    
                    datos[0] = result.getString(1);
                    datos[1] = result.getString(2);
                    datos[2] = result.getString(3);
                    datos[3] = result.getString(4);
                    datos[4] = result.getString(5);
                    datos[5] = result.getString(6);
                    datos[6] = result.getString(7);
                    tcliente.addRow(datos);//se agregan filas segun se vayan encontrando datos en la tabla de la BD
                    
                    tablaCliente.setModel(tcliente);//Se coloca el modelo en en la tabla para mostrarla
                }else{
                    jLabel_aviso.setText("No se hayo ID en la BD");
                }
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e+" ID no se encuentra en la base de datos");
        }
        
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jTxt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_nombreActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        
        String ced = jTxt_cedula.getText();
        String dato;
        
        DefaultTableModel tcliente = new DefaultTableModel();
        tcliente.addColumn("CÉDULA");
        tcliente.addColumn("NOMBRE");
        tcliente.addColumn("TELÉFONO");
        tcliente.addColumn("SEXO");
        tcliente.addColumn("ESTADO");
        tcliente.addColumn("DIRECCIÓN");
        tcliente.addColumn("FECHA NAC.");
        tablaCliente.setModel(tcliente);
        
        //se realiza un arreglo
        String []datos = new String[7];
        
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/clientes","root","");
            
            PreparedStatement pst1 = c.prepareStatement("DELETE FROM tabla1 WHERE cedula = ?");
            pst1.setString(1, jTxt_cedula.getText().trim());
            pst1.executeUpdate();
            
            PreparedStatement pst = c.prepareStatement("INSERT INTO "
                    + "tabla1(cedula,nombre,telefono,sexo,estado,direccion,fecha) values (?,?,?,?,?,?,?) ");


            pst.setString(1, jTxt_cedula.getText().trim());
            pst.setString(2, jTxt_nombre.getText().trim());
            pst.setString(3, jTxt_telefono.getText().trim());
            pst.setString(4, jTxt_sexo.getText().trim());
            pst.setString(5, jTxt_estado.getText().trim());
            pst.setString(6, jTxt_direccion.getText().trim());
            pst.setString(7, jTxt_fecha.getText().trim());
            pst.executeUpdate();

            jTxt_nombre.setText("");
            jTxt_telefono.setText("");
            jTxt_sexo.setText("");
            jTxt_estado.setText("");
            jTxt_direccion.setText("");
            jTxt_fecha.setText("");
            jTxt_cedula.setText("");
            
            Statement leer = conect.createStatement();
            ResultSet result = leer.executeQuery("select * from tabla1"); //Se verifica toda la información de la tabla
            
            while (result.next()) { //mientras se encuentren valores siguientes
                dato = result.getString(1);
                if(dato.equals(ced)){
                    datos[0] = result.getString(1);
                    datos[1] = result.getString(2);
                    datos[2] = result.getString(3);
                    datos[3] = result.getString(4);
                    datos[4] = result.getString(5);
                    datos[5] = result.getString(6);
                    datos[6] = result.getString(7);
                    tcliente.addRow(datos);//se agregan filas segun se vayan encontrando datos en la tabla de la BD
                    tablaCliente.setModel(tcliente);//Se coloca el modelo en en la tabla para mostrarla
                }
            }

            jLabel_verificacion.setText("Actualización de Datos Exitosa");

        } catch (Exception e) {
            }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Volver;
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_aviso;
    private javax.swing.JLabel jLabel_verificacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxt_cedula;
    private javax.swing.JTextField jTxt_direccion;
    private javax.swing.JTextField jTxt_estado;
    private javax.swing.JTextField jTxt_fecha;
    private javax.swing.JTextField jTxt_nombre;
    private javax.swing.JTextField jTxt_sexo;
    private javax.swing.JTextField jTxt_telefono;
    public javax.swing.JTable tablaCliente;
    // End of variables declaration//GEN-END:variables
}
